// Auto-generated by graph_gallery/scripts/refresh_manifest.ps1
window.GRAPH_MANIFEST = {
    "graphs":  [
                   {
                       "id":  "ackland2008_shoulder_adductors_interactive",
                       "title":  "Adduction IMALs",
                       "file":  "views/ackland2008_shoulder_adductors_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T01:41:34.0580065-04:00"
                   },
                   {
                       "id":  "murray1995_elbow_flexor_imal_interactive",
                       "title":  "Elbow flexor IMAL",
                       "file":  "views/murray1995_elbow_flexor_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T00:52:01.7084520-04:00"
                   },
                   {
                       "id":  "ackland2011_neck_imal_interactive",
                       "title":  "Neck IMAL",
                       "file":  "views/ackland2011_neck_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T01:04:26.1618186-04:00"
                   },
                   {
                       "id":  "digitizer",
                       "title":  "Digitizer",
                       "file":  "views/digitizer.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T01:16:45.0265277-04:00"
                   }
               ],
    "generatedAt":  "2026-03-16T01:41:40.4310624-04:00"
};

