// Auto-generated by graph_gallery/scripts/refresh_manifest.ps1
window.GRAPH_MANIFEST = {
    "graphs":  [
                   {
                       "id":  "ackland2008_shoulder_adductors_interactive",
                       "title":  "Adduction IMALs",
                       "file":  "views/ackland2008_shoulder_adductors_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:43:39.0442452-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_abduction_imal_interactive",
                       "title":  "Abduction IMALs",
                       "file":  "views/ackland2008_shoulder_abduction_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:43:39.0432446-04:00"
                   },
                   {
                       "id":  "kuechle1997_shoulder_imal_interactive",
                       "title":  "Kuechle Shoulder IMALs",
                       "file":  "views/kuechle1997_shoulder_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:55:01.9892073-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_flexion_imal_interactive",
                       "title":  "Flexion IMALs",
                       "file":  "views/ackland2008_shoulder_flexion_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3254443-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_extension_imal_interactive",
                       "title":  "Extension IMALs",
                       "file":  "views/ackland2008_shoulder_extension_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3254443-04:00"
                   },
                   {
                       "id":  "murray1995_elbow_flexor_imal_interactive",
                       "title":  "Elbow flexor IMAL",
                       "file":  "views/murray1995_elbow_flexor_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:46:34.0609916-04:00"
                   },
                   {
                       "id":  "ettema1998_upper_limb_imal_interactive",
                       "title":  "Ettema IMALs",
                       "file":  "views/ettema1998_upper_limb_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T18:15:00.0000000-04:00"
                   },
                   {
                       "id":  "buford1997_knee_extension_imal_interactive",
                       "title":  "Knee extension IMAL",
                       "file":  "views/buford1997_knee_extension_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T18:40:00.0000000-04:00"
                   },
                   {
                       "id":  "nemeth1985_hip_extension_imal_interactive",
                       "title":  "Hip extension IMAL",
                       "file":  "views/nemeth1985_hip_extension_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T19:05:00.0000000-04:00"
                   },
                   {
                       "id":  "song2020_hip_abduction_imal_interactive",
                       "title":  "Hip abduction IMAL",
                       "file":  "views/song2020_hip_abduction_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T19:48:00.0000000-04:00"
                   },
                   {
                       "id":  "kleinhorsman2007_hip_adduction_imal_interactive",
                       "title":  "Hip adduction IMAL",
                       "file":  "views/kleinhorsman2007_hip_adduction_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T22:32:00.0000000-04:00"
                   },
                   {
                       "id":  "ackland2011_neck_imal_interactive",
                       "title":  "Neck IMAL",
                       "file":  "views/ackland2011_neck_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T18:17:27.9348898-04:00"
                   },
                   {
                       "id":  "digitizer",
                       "title":  "Digitizer",
                       "file":  "views/digitizer.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T01:16:45.0265277-04:00"
                   }
               ],
    "generatedAt":  "2026-03-17T22:32:00.0000000-04:00"
};


