// Auto-generated by graph_gallery/scripts/refresh_manifest.ps1
window.GRAPH_MANIFEST = {
    "graphs":  [
                   {
                       "id":  "ackland2008_shoulder_adductors_interactive",
                       "title":  "Adduction IMALs",
                       "file":  "views/ackland2008_shoulder_adductors_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3254443-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_abduction_imal_interactive",
                       "title":  "Abduction IMALs",
                       "file":  "views/ackland2008_shoulder_abduction_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3244449-04:00"
                   },
                   {
                       "id":  "kuechle1997_shoulder_imal_interactive",
                       "title":  "Kuechle Shoulder IMALs",
                       "file":  "views/kuechle1997_shoulder_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T18:17:27.9348898-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_flexion_imal_interactive",
                       "title":  "Flexion IMALs",
                       "file":  "views/ackland2008_shoulder_flexion_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3254443-04:00"
                   },
                   {
                       "id":  "ackland2008_shoulder_extension_imal_interactive",
                       "title":  "Extension IMALs",
                       "file":  "views/ackland2008_shoulder_extension_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:33.3254443-04:00"
                   },
                   {
                       "id":  "murray1995_elbow_flexor_imal_interactive",
                       "title":  "Elbow flexor IMAL",
                       "file":  "views/murray1995_elbow_flexor_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-17T01:37:47.1559668-04:00"
                   },
                   {
                       "id":  "ackland2011_neck_imal_interactive",
                       "title":  "Neck IMAL",
                       "file":  "views/ackland2011_neck_imal_interactive.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T18:17:27.9348898-04:00"
                   },
                   {
                       "id":  "digitizer",
                       "title":  "Digitizer",
                       "file":  "views/digitizer.html",
                       "kind":  "interactive",
                       "updatedAt":  "2026-03-16T01:16:45.0265277-04:00"
                   }
               ],
    "generatedAt":  "2026-03-17T01:40:51.1648948-04:00"
};

