$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $PSScriptRoot
$graphsDir = Join-Path $root "graphs"
$manifestPath = Join-Path $root "manifest.js"
$interactivePath = Join-Path $root "interactive_graphs.json"

New-Item -ItemType Directory -Force -Path $graphsDir | Out-Null

$exts = @("*.png", "*.jpg", "*.jpeg", "*.gif", "*.webp", "*.bmp")
$files = @()
foreach ($ext in $exts) {
  $files += Get-ChildItem -Path $graphsDir -File -Filter $ext -ErrorAction SilentlyContinue
}
$files = $files | Sort-Object Name

function To-Title([string]$name) {
  $base = [System.IO.Path]::GetFileNameWithoutExtension($name)
  $base = $base -replace "_", " "
  $base = $base -replace "-", " "
  $base = $base -replace "\s+", " "
  $base = $base.Trim()
  if ([string]::IsNullOrWhiteSpace($base)) { return $name }
  # Title-case-ish
  return ($base.Substring(0,1).ToUpper() + $base.Substring(1))
}

$graphs = foreach ($f in $files) {
  [pscustomobject]@{
    id = [System.IO.Path]::GetFileNameWithoutExtension($f.Name)
    title = (To-Title $f.Name)
    file = $f.Name
    kind = ($f.Extension.TrimStart(".").ToLower())
    updatedAt = $f.LastWriteTime.ToString("o")
  }
}

$interactive = @()
$replaces = @()
if (Test-Path $interactivePath) {
  try {
    $interactive = (Get-Content -Raw -Path $interactivePath | ConvertFrom-Json)
  } catch {
    throw "Failed to parse $interactivePath. Fix JSON and rerun."
  }

  foreach ($it in @($interactive)) {
    if ($null -ne $it.replacesFiles) { $replaces += @($it.replacesFiles) }
  }

  $interactive = @($interactive) | ForEach-Object {
    $filePath = Join-Path $root $_.file
    $updatedAt = $null
    if (Test-Path $filePath) {
      $updatedAt = (Get-Item $filePath).LastWriteTime.ToString("o")
    }
    [pscustomobject]@{
      id = $_.id
      title = $_.title
      file = $_.file
      kind = $_.kind
      updatedAt = $updatedAt
    }
  }
}

# If an interactive graph replaces a static image, hide that static entry from the gallery list.
if (@($replaces).Count -gt 0) {
  $replSet = @{} # string -> bool
  foreach ($r in @($replaces)) { if ($null -ne $r) { $replSet[[string]$r] = $true } }
  $graphs = @($graphs) | Where-Object { -not $replSet.ContainsKey([string]$_.file) }
}

$generatedAt = (Get-Date).ToString("o")
$json = @{ generatedAt = $generatedAt; graphs = @(@($graphs) + @($interactive)) } | ConvertTo-Json -Depth 6

$content = @()
$content += "// Auto-generated by graph_gallery/scripts/refresh_manifest.ps1"
$content += "window.GRAPH_MANIFEST = $json;"
$content += ""

Set-Content -Path $manifestPath -Value $content -Encoding UTF8
Write-Host "Wrote $manifestPath"
Write-Host ("Graphs: {0}" -f (@(@($graphs) + @($interactive))).Count)
